### PR TITLE
Use the subdomain to select country

### LINKED ISSUE #19: Game starts with France on world
The game always starts with France selected in the `select.countrySelect`. Instead, it should use either the country for the domain (ie. Switzerland for `ch.openfoodfacts.org`) or none (`world.openfoodfacts.org`). Defaulting to France is unexpected behaviour if opened from another countries' OFF subdomain.

https://github.com/openfoodfacts/openfoodfacts-hungergames/blob/1c74f58f066bc21c9ec20bc0122329219c97125f/src/Questions/index.js#L11

### PR DESCRIPTION
**Pull request by hangy**
Use the OFF subdomain to determine the initial country to select from the dropdown.

Fixes #19

### CODE REVIEW

File: src/Questions/index.js [hunk 1]
```diff
@@ -152,9 +173,9 @@ const Questions = () => {
         value={country}
         onChange={e => setCountry(e.target.value)}
       >
-        {Object.entries(countries).map(([id, label]) => (
-          <option key={id} value={id}>
-            {label}
+        {Object.entries(countries).map(([_, value]) => (
```
Comment (ArnaudBarre) [inline src/Questions/index.js]: Like countries is a list now you can simplify with:
`{countries.map(country =>` or `{countries.map(({ id, label }) =>` if you like destructuring like me :)

File: src/Questions/index.js [hunk 2]
```diff
@@ -8,28 +8,45 @@ const NO_QUESTION_REMAINING = 'NO_QUESTION_REMAINING';
...
+    if (matches[3]) {
+      return { subDomain: matches[1], cc: cc, lc: matches[3] };
+    }
+
+    const country = countries.find(
+      country => country.cc !== undefined && country.cc.toLowerCase() === cc,
+    );
+    const lc = country === undefined ? 'en' : country.lc;
+    return { subDomain: matches[1], cc: cc, lc: lc };
   })();
```
Comment (ArnaudBarre) [inline src/Questions/index.js]: I should have done this before but if you can put this function outside of the component render, no need to do it each time :)

**Review by ArnaudBarre — COMMENTED** [review]
Thank for fixing this by yourself !

I think you can merge this PR and closed the two others.

I added two minor feedback.

A change that could be good for others is to avoid `lc` and `cc` abbreviations, this makes the code less readable I found

File: src/Questions/index.js (hunk 1 above)
Comment (hangy) [reply src/Questions/index.js]: Thanks, fixed in 183634552d6ab514eb542c236bc8ba5b063f0bf7.

File: src/Questions/index.js (hunk 2 above)
Comment (hangy) [reply src/Questions/index.js]: True, that's a bit redundant since the subdomain shouldn't really change after the site was loaded (or we wouldn't care). Fixed in 3be24fd3b4edbcfe49f99e3bd6bd5a66e2cbb4ed.

**Comment by hangy** [comment]
Thanks for your feedback, @ArnaudBarre! I've addressed your comments and updated the PR accordingly. Let's see what GitHub does to the other PRs if this one is merged. 😉

**Review by ArnaudBarre — APPROVED** [review]
Looks great! There is a little console.log left but it's not harmful ;)

**Comment by hangy** [comment]
>There is a little console.log left but it's not harmful ;)

How did I miss that? :confused: :smile:

File: src/Questions/index.js [hunk 3]
```diff
@@ -6,28 +6,58 @@ import './questions.css';
 
 const NO_QUESTION_REMAINING = 'NO_QUESTION_REMAINING';
 
+const subDomain = (() => {
+  console.log(window.location.href);
```
Comment (VaiTon) [inline src/Questions/index.js]: Remove this console.log

**Review by VaiTon — CHANGES_REQUESTED** [review]
😄

**Comment by ArnaudBarre** [comment]
Oh effectively GitHub considered the two other PRs merged, I didn't know about his feature :)
